IF DB_ID(N'RoomBooking') IS NULL CREATE DATABASE RoomBooking;
GO
USE RoomBooking;
GO
IF OBJECT_ID(N'dbo.Companies', N'U') IS NULL
CREATE TABLE Companies (Id INT IDENTITY PRIMARY KEY, Name NVARCHAR(200) NOT NULL, Code NVARCHAR(50) NOT NULL UNIQUE, CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME());
IF OBJECT_ID(N'dbo.MeetingRooms', N'U') IS NULL
CREATE TABLE MeetingRooms (Id INT IDENTITY PRIMARY KEY, CompanyId INT NOT NULL, Name NVARCHAR(200) NOT NULL, Location NVARCHAR(200) NOT NULL DEFAULT '', Capacity INT NOT NULL, Equipment NVARCHAR(500) NOT NULL DEFAULT '', IsActive BIT NOT NULL DEFAULT 1, CONSTRAINT FK_MeetingRooms_Companies FOREIGN KEY (CompanyId) REFERENCES Companies(Id));
IF OBJECT_ID(N'dbo.Reservations', N'U') IS NULL
CREATE TABLE Reservations (Id INT IDENTITY PRIMARY KEY, CompanyId INT NOT NULL, MeetingRoomId INT NOT NULL, Subject NVARCHAR(250) NOT NULL, ReservedBy NVARCHAR(200) NOT NULL, StartAt DATETIME2 NOT NULL, EndAt DATETIME2 NOT NULL, Status NVARCHAR(30) NOT NULL DEFAULT 'Confirmed', CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(), CONSTRAINT FK_Reservations_Companies FOREIGN KEY (CompanyId) REFERENCES Companies(Id), CONSTRAINT FK_Reservations_MeetingRooms FOREIGN KEY (MeetingRoomId) REFERENCES MeetingRooms(Id));
IF NOT EXISTS (SELECT 1 FROM Companies WHERE Code='MAKUB') INSERT INTO Companies(Name,Code) VALUES (N'Makub Center', 'MAKUB');
IF NOT EXISTS (SELECT 1 FROM MeetingRooms) INSERT INTO MeetingRooms(CompanyId,Name,Location,Capacity,Equipment) SELECT Id,N'Makub A',N'ชั้น 1',8,N'จอ TV, Whiteboard' FROM Companies WHERE Code='MAKUB';
GO
